theme = 'PaperMod'

baseurl = "https://sophia.github.io" 
#設定主頁 url

languageCode = "zh-tw" 
#設定 Blog 語言

title = "2023.7.4" 
#設定網站標題

buildDrafts = false 
#是否產生草稿(建議選否)

[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10

[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30

[params.profileMode]
enabled = true
title = "1123"
subtitle = "TT"
imageUrl = "img/1.gif"
imageWidth = 120
imageHeight = 120
imageTitle = "2023.7.4"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/sophia1123"
#...more

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視